# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ajuntament de Barcelona
email: github@bcn.cat
description: Repositoris de l'Ajuntament de Barcelona. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin finibus molestie arcu consequat rutrum. Mauris bibendum turpis sapien, eu interdum mi egestas at. In non massa a nisi tempus dapibus. Aenean efficitur nisi in consequat vestibulum. Suspendisse vestibulum magna et posuere auctor. Donec varius imperdiet rhoncus. Nullam iaculis varius eros nec placerat. Cras id tristique mauris, id luctus est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus eu scelerisque dolor. Cras eu congue nisi, eget cursus nulla.
#baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
